<?php


// Old documentation routes
$redirects = array(
	'general'  										=> 'about',
	'general/about/changelog'						=> 'about/changelog',
	'general/about/license'							=> 'about/license',
	'general/about/nitrocms-versions'				=> 'about/nitrocms-versions',
	'general/about/languages'						=> 'about/languages',
	'general/getting-started/server-requirements' 	=> 'setup/server-requirements',
	'general/getting-started/installation' 			=> 'setup/installation',
	'general/getting-started/removing-indexphp-from-urls' => 'setup/removing-indexphp-from-urls',
	'general/getting-started/environments' 			=> 'setup/environments',
	'general/getting-started/nitrocms-folder-structure' => 'setup/nitrocms-folder-structure',
	'general/basics/the-control-panel' 				=> 'concepts/the-control-panel',
	'general/basics/organization' 					=> 'concepts/organization',
	'general/basics/nitrocms-tags' 					=> 'concepts/nitrocms-tags',
	'general/basics/nitrocms-urls' 					=> 'concepts/nitrocms-urls',
	'general/basics/themes' 						=> 'concepts/themes',
	'general/basics/widgets-plugins-and-modules' 	=> 'concepts/widgets-plugins-and-modules',
	'general/basics/add-ons' 						=> 'concepts/add-ons',
	'modules-and-tags/tag-reference/blog' 			=> 'modules-and-tags/blog',
	'modules-and-tags/tag-reference/contact' 		=> 'modules-and-tags/contact',
	'modules-and-tags/tag-reference/files' 			=> 'modules-and-tags/files',
	'modules-and-tags/tag-reference/galleries' 		=> 'modules-and-tags/galleries',
	'modules-and-tags/tag-reference/global' 		=> 'modules-and-tags/global',
	'modules-and-tags/tag-reference/helper' 		=> 'modules-and-tags/helper',
	'modules-and-tags/tag-reference/lang' 			=> 'modules-and-tags/lang',
	'modules-and-tags/tag-reference/navigation' 	=> 'modules-and-tags/navigation',
	'modules-and-tags/tag-reference/session' 		=> 'modules-and-tags/session',
	'modules-and-tags/tag-reference/settings' 		=> 'modules-and-tags/settings',
	'modules-and-tags/tag-reference/theme' 			=> 'modules-and-tags/theme',
	'modules-and-tags/tag-reference/url' 			=> 'modules-and-tags/url',
	'modules-and-tags/tag-reference/user' 			=> 'modules-and-tags/user',
	'modules-and-tags/tag-reference/variables' 		=> 'modules-and-tags/variables',
	'modules-and-tags/tag-reference/widgets' 		=> 'modules-and-tags/widgets',
	'nitrocms-pro/features/multi-site-manager' 		=> 'pro/features/multi-site-manager',
	'pro/features/nitrostreams' 					=> 'modules-and-tags/streams'
);